Change in workflow config

diff --git a/.github/workflows/tf-plan-apply-destroy.yml b/.github/workflows/tf-plan-apply-destroy.yml
--- a/.github/workflows/tf-plan-apply-destroy.yml
+++ b/.github/workflows/tf-plan-apply-destroy.yml
@@ -14,6 +14,12 @@ on:
       - 'tf/**'
       - '.github/workflows/**'
   workflow_dispatch:
+    inputs:
+      destroy:
+        description: 'Destroy resources?'
+        required: false
+        default: false
+        type: boolean
 
 #Special permissions required for OIDC authentication
 permissions:
@@ -31,6 +37,7 @@ jobs:
   terraform-plan:
     name: 'Terraform Plan'
     runs-on: ubuntu-latest
+    if:  ${{ ! inputs.destroy }}
     defaults:
       run:
         shell: bash
@@ -162,16 +169,115 @@ jobs:
       run: |
         terraform apply -auto-approve terraform.tfplan
 
+  terraform-plan-destroy:
+    name: 'Terraform Plan Destroy'
+    runs-on: ubuntu-latest
+    if:  ${{ inputs.destroy }}
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./tf
+    env:
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
+
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_wrapper: false
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
+
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -var-file='variables/dev.tfvars' -destroy -detailed-exitcode -no-color -out terraform.tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v4
+      with:
+        name: tfplan
+        path: tf/terraform.tfplan
+        
+    # Create string output of Terraform Plan
+    - name: Create String Output
+      id: tf-plan-string
+      run: |
+        TERRAFORM_PLAN=$(terraform show -no-color terraform.tfplan)
+        
+        delimiter="$(openssl rand -hex 8)"
+        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+        echo "" >> $GITHUB_OUTPUT
+        echo '```terraform' >> $GITHUB_OUTPUT
+        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+        echo '```' >> $GITHUB_OUTPUT
+        echo "</details>" >> $GITHUB_OUTPUT
+        echo "${delimiter}" >> $GITHUB_OUTPUT
+        
+    # Publish Terraform Plan as task summary
+    - name: Publish Terraform Plan to Task Summary
+      env:
+        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+      run: |
+        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+    # If this is a PR post the changes
+    - name: Push Terraform Output to PR
+      if: github.ref != 'refs/heads/main'
+      uses: actions/github-script@v7
+      env:
+        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+      with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const body = `${process.env.SUMMARY}`;
+            github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: body
+            })
+                
   terraform-destroy:
     name: 'Terraform Destroy'
-    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 0
+    if: github.ref == 'refs/heads/main' && needs.terraform-plan-destroy.outputs.tfplanExitCode == 2
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
         working-directory: ./tf
     environment: DEV-Destroy
-    needs: [terraform-plan]
+    needs: [terraform-plan-destroy]
     
     steps:
     # Checkout the repository to the GitHub Actions runner
@@ -186,7 +292,14 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    # Terraform Destroy
-    - name: Terraform  Destroy
+    # Download saved plan from artifacts
+    - name: Download Terraform Plan
+      uses: actions/download-artifact@v4
+      with:
+        path: tf
+        name: tfplan
+
+    # Terraform Apply
+    - name: Terraform Apply
       run: |
-        terraform destroy -var-file='variables/dev.tfvars'
+        terraform apply -auto-approve terraform.tfplan
